import React, { createContext, useContext, useState, useEffect, useRef } from 'react';
import { io } from 'socket.io-client';
import { useAuth } from './AuthContext';

const VideoContext = createContext();

export const useVideo = () => useContext(VideoContext);

const ICE_SERVERS = {
  iceServers: [
    { urls: 'stun:stun.l.google.com:19302' },
    { urls: 'stun:stun1.l.google.com:19302' },
  ],
};

export const VideoProvider = ({ children }) => {
  const { token, user } = useAuth();
  const [socket, setSocket] = useState(null);
  const [localStream, setLocalStream] = useState(null);
  const [remoteStream, setRemoteStream] = useState(null);
  const [isCalling, setIsCalling] = useState(false);
  const [callEnded, setCallEnded] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [onlineDoctors, setOnlineDoctors] = useState([]);

  const peerConnectionRef = useRef(null);
  const localVideoTrackRef = useRef(null);
  const localAudioTrackRef = useRef(null);

  // Initialize socket connection
  useEffect(() => {
    if (!token) {
      if (socket) socket.disconnect();
      return;
    }

    const socketUrl = import.meta.env.VITE_API_URL || 'http://localhost:5000';
    const newSocket = io(socketUrl, {
      auth: { token },
      transports: ['websocket'],
    });

    newSocket.on('connect', () => {
      console.log('Socket.io connected:', newSocket.id);
    });

    newSocket.on('doctor-online', (data) => {
      console.log('Doctor went online:', data);
      setOnlineDoctors((prev) => {
        if (prev.some((doc) => doc.doctorId === data.doctorId)) return prev;
        return [...prev, data];
      });
    });

    newSocket.on('appointment-confirmed', (data) => {
      console.log('Appointment confirmed via socket:', data);
      alert(data.message);
    });

    newSocket.on('connect_error', (err) => {
      console.error('Socket connection error:', err.message);
      setErrorMessage('Signaling connection error. Real-time features might be limited.');
    });

    setSocket(newSocket);

    return () => {
      newSocket.disconnect();
    };
  }, [token]);

  // Clean up streams & peer connection
  const destroyCall = () => {
    if (peerConnectionRef.current) {
      peerConnectionRef.current.close();
      peerConnectionRef.current = null;
    }
    if (localStream) {
      localStream.getTracks().forEach((track) => track.stop());
    }
    setLocalStream(null);
    setRemoteStream(null);
    setIsCalling(false);
    setCallEnded(true);
  };

  // Join Room and setup WebRTC connection
  const startCall = async (appointmentId) => {
    try {
      setErrorMessage('');
      setCallEnded(false);
      setIsCalling(true);

      // 1. Get media devices
      const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true });
      setLocalStream(stream);
      
      localVideoTrackRef.current = stream.getVideoTracks()[0];
      localAudioTrackRef.current = stream.getAudioTracks()[0];

      // 2. Connect to socket room
      if (socket) {
        socket.emit('join-room', { appointmentId });
      }

      // 3. Create peer connection
      const pc = new RTCPeerConnection(ICE_SERVERS);
      peerConnectionRef.current = pc;

      // Add local stream tracks to PC
      stream.getTracks().forEach((track) => {
        pc.addTrack(track, stream);
      });

      // Handle ice candidates generated by browser
      pc.onicecandidate = (event) => {
        if (event.candidate && socket) {
          socket.emit('ice-candidate', { appointmentId, candidate: event.candidate });
        }
      };

      // Handle remote stream tracks
      pc.ontrack = (event) => {
        console.log('Received remote track event');
        if (event.streams && event.streams[0]) {
          setRemoteStream(event.streams[0]);
        }
      };

      // Listen for signaling events from socket
      if (socket) {
        // Clear previous listeners to avoid duplicates
        socket.off('user-joined');
        socket.off('offer');
        socket.off('answer');
        socket.off('ice-candidate');
        socket.off('call-ended');

        // When other user joins, create offer (if doctor/caller)
        socket.on('user-joined', async () => {
          console.log('Other user joined. Generating offer...');
          const offer = await pc.createOffer();
          await pc.setLocalDescription(offer);
          socket.emit('offer', { appointmentId, offer });
        });

        // Receive offer and generate answer
        socket.on('offer', async ({ offer }) => {
          console.log('Received offer. Creating answer...');
          await pc.setRemoteDescription(new RTCSessionDescription(offer));
          const answer = await pc.createAnswer();
          await pc.setLocalDescription(answer);
          socket.emit('answer', { appointmentId, answer });
        });

        // Receive answer
        socket.on('answer', async ({ answer }) => {
          console.log('Received answer.');
          await pc.setRemoteDescription(new RTCSessionDescription(answer));
        });

        // Receive ICE candidate
        socket.on('ice-candidate', async ({ candidate }) => {
          try {
            console.log('Received remote ICE candidate.');
            await pc.addIceCandidate(new RTCIceCandidate(candidate));
          } catch (e) {
            console.error('Error adding received ice candidate', e);
          }
        });

        // Handle remote user ending call
        socket.on('call-ended', () => {
          console.log('Call was ended by remote peer.');
          destroyCall();
        });
      }
    } catch (err) {
      console.error('WebRTC initialization failed:', err);
      setErrorMessage(
        err.name === 'NotAllowedError'
          ? 'Permission denied: Please allow access to your camera and microphone.'
          : 'Could not access camera/microphone. Please verify hardware connections.'
      );
      setIsCalling(false);
    }
  };

  const endCall = (appointmentId) => {
    if (socket) {
      socket.emit('call-ended', { appointmentId });
    }
    destroyCall();
  };

  const toggleCamera = (enabled) => {
    if (localVideoTrackRef.current) {
      localVideoTrackRef.current.enabled = enabled;
    }
  };

  const toggleMic = (enabled) => {
    if (localAudioTrackRef.current) {
      localAudioTrackRef.current.enabled = enabled;
    }
  };

  return (
    <VideoContext.Provider
      value={{
        socket,
        localStream,
        remoteStream,
        isCalling,
        callEnded,
        errorMessage,
        onlineDoctors,
        startCall,
        endCall,
        toggleCamera,
        toggleMic,
      }}
    >
      {children}
    </VideoContext.Provider>
  );
};
